-- Generated by engine.research.staging; do not edit.
-- Plan SHA-256: a75762db08e915835df63c5dacdd7228bfa8e831d6f713313e0405e33322587e
begin isolation level repeatable read;
set local lock_timeout = '10s';
set local statement_timeout = '180s';
select pg_advisory_xact_lock(
  hashtextextended('computerecord:identity-staging-load', 0)
);
do $identity_load$
declare
  existing_state core.identity_staging_state;
  existing_sha text;
  canonical_entity_count bigint;
  fact_version_count bigint;
begin
  select count(*) into canonical_entity_count from core.entity;
  select count(*) into fact_version_count from core.fact_version;
  select b.state, b.plan_sha256 into existing_state, existing_sha
  from core.identity_staging_batch b where b.id = '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid;
  if found then
    if existing_state <> 'sealed' or existing_sha <> 'a75762db08e915835df63c5dacdd7228bfa8e831d6f713313e0405e33322587e' then
      raise exception 'identity staging batch exists in a different state';
    end if;
    perform core.seal_identity_staging_batch('0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'a75762db08e915835df63c5dacdd7228bfa8e831d6f713313e0405e33322587e');
    return;
  end if;
  insert into core.identity_staging_batch (
    id, plan_sha256, classification, expected_review_packets,
    expected_identity_candidates, expected_canonical_ready,
    expected_canonical_blocked, expected_blocker_count
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'a75762db08e915835df63c5dacdd7228bfa8e831d6f713313e0405e33322587e', 'sealed_identity_staging_plan',
    3, 10,
    5, 5,
    5
  );
  insert into core.identity_staging_input (
    batch_id, packet_key, review_id, decision_id, merge_commit,
    claims_sha256, entity_seeds_sha256, review_manifest_sha256,
    review_decision_sha256
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'beacon-point-sec-8k',
    '770e202d-a8d0-5077-b532-107121a2350e'::uuid, '464efbc6-bf7f-5f8c-b4a7-145f337c71b2'::uuid,
    '3a9948a11cf6ebc130aa276ea697d14fa9709969', 'caa6e58dba6d26de9f4b09111084083aeb7d57a35d2927f5743999a49f0781fa',
    '26e7e29936861522fb81a8cb55272414b1000406ad22d6209da701c05b92b6c9',
    '81729136e6036a4e1ae10076fdb2797020cf600480163229fae27744a562324f',
    '4c297b7937317c752a4c6e32e27e5977915ecfd13d5caa75d969daa3402921bb'
  );
  insert into core.identity_staging_input (
    batch_id, packet_key, review_id, decision_id, merge_commit,
    claims_sha256, entity_seeds_sha256, review_manifest_sha256,
    review_decision_sha256
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'childress-sec-10q',
    'b034c0d8-239f-59ee-a915-c5844d7385ba'::uuid, 'b18fe95c-e5c3-53ab-8866-51e7e2e2f923'::uuid,
    '5edb1b9a9d3a3b30e081376f4a54d3a489aa5677', '12cab1cec8aad7bab571965c6eb5e97c01d79250d7787a60d5e9ba56abe2d96d',
    'd1c56d793e0ddb71a6b1eda2c493d96e87762011a98e8dc4a2071b4e589e9634',
    '5ad68e713576fdda5c263c1118ce2398591bc056796aa23d8f6cc39d2129084b',
    '8f4b41b883cdfa2fb9d5e499af9da3786735d1c03ba18f54fc34c38f91d93255'
  );
  insert into core.identity_staging_input (
    batch_id, packet_key, review_id, decision_id, merge_commit,
    claims_sha256, entity_seeds_sha256, review_manifest_sha256,
    review_decision_sha256
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'delta-forge-1-sec-8k',
    '9a5ea3df-f0a9-52cb-94c9-2ba3b6d33565'::uuid, '06aeb18d-e80f-5062-91b5-ff7668c2977f'::uuid,
    '1bccbfba7c3315af81722589361b64afc05fc6d5', '3a8e5665db44758b0afaab5bf3953f7f16ea23156816f0888d38d725fd593fee',
    '7ced15447aa48389b18fd68578252ea784a1c098ac4d820ac1c69c99ba9a7765',
    '6478e73ae7630ad6fedd201d969e2920eb68447856e5bf4d134fb33b915a7566',
    'bd5c2cd9197cb64d75f4b71f6d44707f6833b039293c6494fd1f87cf577b35f3'
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '14a6e0aa-66e0-5752-8cc2-0833066b9dd9'::uuid,
    'organization-hut-8-corporation', 'organization',
    'Hut 8 Corporation', '{}'::jsonb,
    array['missing_organization_type']::text[],
    '464efbc6-bf7f-5f8c-b4a7-145f337c71b2'::uuid
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '14a6e0aa-66e0-5752-8cc2-0833066b9dd9'::uuid, 'HUT'
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '14a6e0aa-66e0-5752-8cc2-0833066b9dd9'::uuid, 'Hut 8'
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '14a6e0aa-66e0-5752-8cc2-0833066b9dd9'::uuid, '44cecdea-b8a0-59e2-a81b-47ccaf61c547'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '14a6e0aa-66e0-5752-8cc2-0833066b9dd9'::uuid, 'c0d7e2b4-20f0-5ff1-b73b-e52c7e63e34b'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '1577c689-09aa-5b3a-8580-406d64b57524'::uuid,
    'organization-beacon-point-dc-llc', 'organization',
    'Beacon Point DC LLC', '{"organization_type":"project_company"}'::jsonb,
    array['unsupported_organization_type:project_company']::text[],
    '464efbc6-bf7f-5f8c-b4a7-145f337c71b2'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '1577c689-09aa-5b3a-8580-406d64b57524'::uuid, '3a820f35-20fd-53ca-8575-ec199b4f0105'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '1577c689-09aa-5b3a-8580-406d64b57524'::uuid, 'c0d7e2b4-20f0-5ff1-b73b-e52c7e63e34b'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '162c5443-42e7-5fb3-ac7f-3b39cfb64663'::uuid,
    'place-childress-texas', 'place',
    'Childress, Texas, United States', '{"city":"Childress","country_code":"US","geo_precision":"city","state":"TX"}'::jsonb,
    '{}'::text[],
    'b18fe95c-e5c3-53ab-8866-51e7e2e2f923'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '162c5443-42e7-5fb3-ac7f-3b39cfb64663'::uuid, '2008738f-6861-503d-b71a-1e619269b5cc'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '162c5443-42e7-5fb3-ac7f-3b39cfb64663'::uuid, '5d6a651b-253a-5467-b0cf-99f48a7f0ea8'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '162c5443-42e7-5fb3-ac7f-3b39cfb64663'::uuid, '8517178c-5ca3-5d91-a25c-f93f938e7baa'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid,
    'campus-iren-childress', 'campus',
    'IREN Childress', '{"canonical_slug":"iren-childress"}'::jsonb,
    '{}'::text[],
    'b18fe95c-e5c3-53ab-8866-51e7e2e2f923'::uuid
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid, 'Childress'
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid, '2008738f-6861-503d-b71a-1e619269b5cc'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid, '5d6a651b-253a-5467-b0cf-99f48a7f0ea8'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid, '8517178c-5ca3-5d91-a25c-f93f938e7baa'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid, 'b2e269b8-6059-5d11-ab15-f9014263023b'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4d856c85-aeab-5169-b374-2f40f2602a6e'::uuid,
    'organization-iren-limited', 'organization',
    'IREN Limited', '{"organization_type":"operator"}'::jsonb,
    '{}'::text[],
    'b18fe95c-e5c3-53ab-8866-51e7e2e2f923'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4d856c85-aeab-5169-b374-2f40f2602a6e'::uuid, '2fabb117-8d7a-501b-8dd8-b4b16af93985'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4d856c85-aeab-5169-b374-2f40f2602a6e'::uuid, 'b2e269b8-6059-5d11-ab15-f9014263023b'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid,
    'campus-beacon-point', 'campus',
    'Beacon Point', '{"canonical_slug":"beacon-point"}'::jsonb,
    '{}'::text[],
    '464efbc6-bf7f-5f8c-b4a7-145f337c71b2'::uuid
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, 'Beacon Point Data Center Project'
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, '06071593-0d7b-5e54-a542-9962871080d2'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, '22f4ee94-3e9c-5901-a580-a8e083f8dd40'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, '3a820f35-20fd-53ca-8575-ec199b4f0105'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, '87ddb2b0-b09f-5ddd-b06a-ad982eb17bfb'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, 'd7589b50-1cb5-5783-b3aa-b01204a21d39'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, 'f86ea41d-12d8-5c92-aade-24608f36d007'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '77bfdbce-c1de-5af0-abea-c08cee7572c5'::uuid,
    'organization-applied-digital-corporation', 'organization',
    'Applied Digital Corporation', '{}'::jsonb,
    array['missing_organization_type']::text[],
    '06aeb18d-e80f-5062-91b5-ff7668c2977f'::uuid
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '77bfdbce-c1de-5af0-abea-c08cee7572c5'::uuid, 'APLD'
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '77bfdbce-c1de-5af0-abea-c08cee7572c5'::uuid, 'Applied Digital'
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '77bfdbce-c1de-5af0-abea-c08cee7572c5'::uuid, '9300a802-402c-54c4-9df4-6b6fdb89fdd7'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '77bfdbce-c1de-5af0-abea-c08cee7572c5'::uuid, 'ef8f8442-5068-54f0-8b55-d5093ffe3f14'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'b171ccc4-476a-5f67-b17f-c612d9c9cfec'::uuid,
    'place-alexandria-louisiana', 'place',
    'Alexandria, Louisiana', '{"city":"Alexandria","geo_precision":"city","state":"LA"}'::jsonb,
    array['missing_country_code']::text[],
    '06aeb18d-e80f-5062-91b5-ff7668c2977f'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'b171ccc4-476a-5f67-b17f-c612d9c9cfec'::uuid, 'a6c5540b-3e00-5827-a53c-eff4eebc8ccb'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'b171ccc4-476a-5f67-b17f-c612d9c9cfec'::uuid, 'b0ad5d36-817d-5b2d-870f-320f35e95ad1'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'c562f3b9-b4c1-561c-8069-92e3309643b7'::uuid,
    'place-nueces-county-texas', 'place',
    'Nueces County, Texas', '{"county":"Nueces","geo_precision":"county","state":"TX"}'::jsonb,
    array['missing_country_code']::text[],
    '464efbc6-bf7f-5f8c-b4a7-145f337c71b2'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'c562f3b9-b4c1-561c-8069-92e3309643b7'::uuid, '22f4ee94-3e9c-5901-a580-a8e083f8dd40'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'c562f3b9-b4c1-561c-8069-92e3309643b7'::uuid, '87ddb2b0-b09f-5ddd-b06a-ad982eb17bfb'::uuid
  );
  insert into core.identity_staging_candidate (
    batch_id, candidate_id, candidate_key, entity_type, canonical_name,
    proposed_attributes, canonical_blockers, source_decision_id
  ) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid,
    'campus-applied-digital-delta-forge-1', 'campus',
    'Applied Digital Delta Forge 1', '{"canonical_slug":"applied-digital-delta-forge-1"}'::jsonb,
    '{}'::text[],
    '06aeb18d-e80f-5062-91b5-ff7668c2977f'::uuid
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid, 'DF1'
  );
  insert into core.identity_staging_alias
    (batch_id, candidate_id, alias) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid, 'Delta Forge 1'
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid, 'a6c5540b-3e00-5827-a53c-eff4eebc8ccb'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid, 'b0ad5d36-817d-5b2d-870f-320f35e95ad1'::uuid
  );
  insert into core.identity_staging_support
    (batch_id, candidate_id, claim_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid, 'ef8f8442-5068-54f0-8b55-d5093ffe3f14'::uuid
  );
  insert into core.identity_staging_dependency
    (batch_id, candidate_id, dependency_candidate_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '353995af-a86b-5fc7-bb37-15c06827ee54'::uuid, '162c5443-42e7-5fb3-ac7f-3b39cfb64663'::uuid
  );
  insert into core.identity_staging_dependency
    (batch_id, candidate_id, dependency_candidate_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, '4f885400-dd74-556e-9f8a-30156f844385'::uuid, 'c562f3b9-b4c1-561c-8069-92e3309643b7'::uuid
  );
  insert into core.identity_staging_dependency
    (batch_id, candidate_id, dependency_candidate_id) values (
    '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'f898b314-b8d6-54c8-9a75-6f3bf1dd1bd7'::uuid, 'b171ccc4-476a-5f67-b17f-c612d9c9cfec'::uuid
  );
  perform core.seal_identity_staging_batch('0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid, 'a75762db08e915835df63c5dacdd7228bfa8e831d6f713313e0405e33322587e');
  if canonical_entity_count <> (select count(*) from core.entity)
     or fact_version_count <> (select count(*) from core.fact_version) then
    raise exception 'identity staging load crossed the canonical boundary';
  end if;
end;
$identity_load$;
commit;
select jsonb_build_object(
  'batch_id', b.id, 'state', b.state, 'plan_sha256', b.plan_sha256,
  'candidates', (select count(*) from core.identity_staging_candidate c where c.batch_id = b.id),
  'ready', (select count(*) from core.identity_staging_candidate c where c.batch_id = b.id and cardinality(c.canonical_blockers) = 0),
  'blocked', (select count(*) from core.identity_staging_candidate c where c.batch_id = b.id and cardinality(c.canonical_blockers) > 0),
  'canonical_entities', (select count(*) from core.entity),
  'facts', (select count(*) from core.fact_version)
) as staging_receipt
from core.identity_staging_batch b where b.id = '0e19f055-e1a9-5153-b7fd-e28be6a0ebff'::uuid;
